import { GrShare } from "react-icons/gr";

export const cardData = [
  {
    images: <img src="/image/Group.png" alt="logo" />,
    title: "Sr. Frontend Developer",
    p1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    p2: "Ut pretium arcu et massa semper, id fringilla leo semper.",
    p3: "Sed quis justo ac magna.",
    p4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dates: "Nov 2021 - Present",
  },
  {
    images: <img src="/image/Group.png" alt="logo" />,
    title: "Team Lead",
    p1: "Sed quis justo ac magna.",
    p2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    p3: "Sed quis justo ac magna.",
    p4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dates: "Jul 2017 - Oct 2021",
  },
  {
    images: <img src="/image/Group.png" alt="logo" />,
    title: "Full Stack Developer",
    p1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    dates: "Dec 2015 - May 2017",
  },
];

export const workCard = [
  {
    images: "/image/Picture.png",
    title: "UBcab",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas necurna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
    skils: [
      "react",
      "next",
      "Typescript",
      "Nest.js",
      "PostgreSQL",
      "Tailwindcss",
      "Figma",
      "Cypress",
      "Storybook",
      "Git",
    ],
    logo: <GrShare />,
  },
  {
    images: "/image/Picture.png",
    title: "UBcab",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas necurna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
    skils: [
      "react",
      "next",
      "Typescript",
      "Nest.js",
      "PostgreSQL",
      "Tailwindcss",
      "Figma",
      "Cypress",
      "Storybook",
      "Git",
    ],
    logo: <GrShare />,
  },
  {
    images: "/image/Picture.png",
    title: "UBcab",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Maecenas necurna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
    skils: [
      "react",
      "next",
      "Typescript",
      "Nest.js",
      "PostgreSQL",
      "Tailwindcss",
      "Figma",
      "Cypress",
      "Storybook",
      "Git",
    ],
    logo: <GrShare />,
  },
];
