export const workcard = [
  {
    name: "Liverger",
    text: " Liveger төсөл 5 хүнтэй баг болж хийсэн. Уг төсөл нь Монгол малчин айлд хажуу гэрээ түрээслэх нүүдэлчин ёс заншлаа таниулах зорилгоор бодож хийсэн төсөл ",
    skills: [
      "React",
      "Nextjs",
      "TailwindCSS",
      "NodeJS",
      "ChadCn UI",
      "Typescript",
      "Vercel",
      "Mongodb",
      "Express",

      "NodeMailer",
    ],
    image: "/image/liveger.png",
    links: "https://liveger.vercel.app/",
  },
  {
    name: "Tinder.com",
    text: "Pinecone дадлага дээр хийсэн төсөл нийт 8 хүнтэй баг бүрдсэн. Шинэ зүйл гэвэл Monorepo, GraphQL, Cypress, Jest дээр ажиллах  Test хийх бас их хүнд байсан.",
    skills: [
      "React",
      "Nextjs",
      "ChadCn UI",
      "Typescript",
      "Node mailer",
      "TailwindCSS",
      "Cloudinary",
      "NodeJS",
      "GraphQl",
      "Apollo",
      "Sypress",
      "Jest",
      "Vercel",
    ],
    image: "/image/tinder1.png",
    links:
      "https://tinder-frontend-prod-pinecone-studio.vercel.app/?fbclid=IwY2xjawJojaZleHRuA2FlbQIxMAABHmFPFxWrtO8pmFY5KVuXXzWtfTt-K3EVifa3cfDLwS-OKPRI87spAzEM3SjJ_aem_VvoahBiqouEqis0fELverw",
  },
  {
    name: "Dansduuren.com",
    webname: "Dansduuren.com",
    text: "Дансдүүрэн ХХК B2B company танилцуулга web site захиалгын дагуу хийж гүйцэтгэсэн. ",
    skills: [
      "React",
      "Nextjs",
      "TailwindCSS",
      "NodeJS",
      "ChadCn UI",
      "javascript",
    ],
    image: "/image/dasnduuren1.png",
    links: "https://dansduuren.com/",
  },
  {
    name: "Dansduuren.com ADMIN",
    text: "Admin хэгэстэй хийсэн шалтгаан нь борлуулалтын компани Brand, Catecory , Product, байнга өөрчлөгдөж байдаг.  Шинэ Brand нэмэгдэх Гэрээт борлуулагч өөрчлөгдөх Мэдээ мэдээлэл ээ шинэчлэх гээд энэ бүгд надтай холбогдохгүйгээр ажиллах боломжийг гаргаж өгсөн .",
    skills: ["Postgre", "Express", "Vercel", "Rest API"],
    image: "/image/admin1.png",
    links: "https://dansduuren.com/login",
  },
];
