export const workcard = [
  {
    name: "Dansduuren.com",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
    skills: [
      "React",
      "Nextjs",
      "HTML",
      "CSS",
      "Tailwind",
      "NodeJS",
      "React",
      "React",
    ],
    image: "/image/ubcab.png",
  },
  {
    name: "Tinder.com",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
    skills: [
      "React",
      "Nextjs",
      "HTML",
      "CSS",
      "Tailwind",
      "NodeJS",
      "React",
      "React",
    ],
    image: "/image/tinder1.png",
  },
  {
    name: "Dansduuren.com",
    webname: "Dansduuren.com",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
    skills: [
      "React",
      "Nextjs",
      "HTML",
      "CSS",
      "Tailwind",
      "NodeJS",
      "React",
      "React",
    ],
    image: "/image/dasnduuren1.png",
  },
  {
    name: "Dansduuren.com ADMIN",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.",
    skills: [
      "React",
      "Nextjs",
      "HTML",
      "CSS",
      "Tailwind",
      "NodeJS",
      "React",
      "React",
    ],
    image: "/image/admin1.png",
  },
];
